server:
  port: 8763
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: netdisk-gateway
  cloud:
    # 设置根据服务ID匹配路由
    gateway:
      # 设置允许跨域请求
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-Headers: "*"
            allowed-Origins: "*"
#            - "http://localhost:8010"
#            - "http://localhost:8020"
#            - "http://localhost:8030"
#            - "http://localhost:8040"
#            - "http://domain.com"
            allowed-Credentials: true
            allowed-Methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTION
      discovery:
        locator:
          enabled: true
          # 设置访问微服务可以用小写的服务名
          lowerCaseServiceId: true
      # 设置路由规则
      routes:
        - id: admin_routes
          # 以 lb:// 开头，后面接eruka注册的服务名
          uri: http://localhost:8010
          # 匹配用户请求
          predicates:
            - Method=GET,POST,PUT,DELETE
            - Path=/admin/**
          filters:
            - StripPrefix=1


        - id: user_routes
          uri: http://localhost:8030
          predicates:
            - Method=GET,POST,PUT,DELETE
            - Path=/user/**
          filters:
            - StripPrefix=1


        - id: file_routes
          uri: http://localhost:8030
          predicates:
            - Method=GET,POST,PUT,DELETE
            - Path=/file/**
          filters:
            - StripPrefix=1


        - id: client_routes
          uri: http://localhost:8040
          predicates:
            - Method=GET
            - Path=/netdisk/v1/**