server:
  port: 8050
spring:
  application:
    name: base
  datasource:
    url: jdbc:mysql://localhost:3306/netdisk?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: 127.0.0.1
